### PR TITLE
[ATX-2023] remove soldout sponsor levels, make covid information prominent

### PR DESCRIPTION
**Pull request by moutons**
cc @nimbinatus @tracypholmes

### CODE REVIEW

**Comment by nimbinatus** [comment]
That's... odd. @moutons, I just rebased off of `devopsdays-web/main`, and yours is still a ton of commits. Where did you create your branch from?

**Comment by nimbinatus** [comment]
Oh! Wait, I know what's wrong. This is a PR against an old branch. The one I'm working off of for the upstream PR is `sponsor-logos`. Fixing!

**Review by nimbinatus — APPROVED** [review]

**Comment by moutons** [comment]
awesome! idk how I got that old branch

**Comment by nimbinatus** [comment]
It wasn't you with the old branch; it was me :) My main isn't rebased.

**Pull request merged**
